spring:
  application:
    name: dubbo-billing-web-consumer
  profiles:
    active: '@activatedProperties@'
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.force: true
    encoding.enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

dubbo:
  application:
    logger: slf4j
  consumer:
    check: false

validation:
  fail:
    fast: false