server:
  port: 1011
  address: 0.0.0.0
  tomcat:
    uri-encoding: utf-8
spring:
  redis:
    database: 0
    host: redis
    port: 6379
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait:

embedded:
  zookeeper:
    port: 2181


dubbo:
  registry:
    address: zookeeper://zookeeper:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
    id: my_registry
  consumer:
    filter: dubboContextFilter

# server properties
jwt:
  secret:
    key:

pwd:
  salt:

logback:
  path: /var/log/log-dubbo-client/