# SPRING PROFILES
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/my_daily_cost_dev?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
  mail:
    host: smtp.yeah.net
    username: tony_sama@yeah.net
    password:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait:
dubbo:
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
    id: my_registry_dev
  provider:
    filter: dubboContextFilter
# server properties
embedded:
  zookeeper:
    port: 2181
    enable: true
rsa:
  key:
    path: doc/

log4j2:
  path: /Users/jiangwenjie/logs/log-dubbo-server/