spring:
  application:
    name: dubbo-billing-server-provider
  profiles:
    active: '@activatedProperties@'
  datasource:
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true
      filter:
        stat:
          enabled: true
        slf4j:
          enabled: true
      filters: slf4j
# MyBatis
mybatis:
  typeAliasesPackage: com.tony.billing.entity
  mapperLocations: classpath:/sqlMapper/*SqlMap.xml
  configLocation: classpath:/mybatis-config.xml
dubbo:
  scan:
    base-packages: com.tony.billing.service

  protocol:
    name: dubbo
    port: -1
  provider:
    filter: dubboContextFilter
# server properties
system:
  host:
    reset:
      password: http://localhost:8080/#/reset/pwd